### ISSUE TITLE
Issues with Vagrant + CentOS 6.7 + Oracle 12.1.0.2

### ISSUE THREAD

**Issue by tischenko** [oravirt/ansible-oracle#3]
Basically, I'm trying to follow this guide https://oravirt.wordpress.com/2014/10/01/getting-started-with-ansible-oracle/ with ansible-oracle from master branch.

Here is my ansible-run stack:
```
TASK: [oradb-create | Create database(s)] *************************************
failed: [localhost] => (item=[{'oracle_init_params': 'open_cursors=300,processes=700', 'is_racone': 'false', 'oracle_db_type': 'SI', 'service_name': 'orcl_serv', 'storage_type': 'FS', 'oracle_db_passwd': 'Oracle123', 'home': 'home1', 'oracle_db_mem_percent': 30, 'is_container': 'false', 'redolog_size_in_mb': 100, 'num_pdbs': 1, 'pdb_prefix': 'pdb', 'oracle_db_name': 'orcl', 'state': 'present', 'oracle_edition': 'EE', 'oracle_database_type': 'MULTIPURPOSE', 'oracle_version_db': '12.1.0.2'}, {'cmd': 'grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l', 'end': '2016-02-29 12:21:00.348156', 'stderr': '', 'stdout': '0', 'changed': True, 'rc': 0, 'item': {'oracle_init_params': 'open_cursors=300,processes=700', 'is_racone': 'false', 'oracle_db_type': 'SI', 'service_name': 'orcl_serv', 'storage_type': 'FS', 'oracle_db_passwd': 'Oracle123', 'home': 'home1', 'oracle_db_mem_percent': 30, 'is_container': 'false', 'redolog_size_in_mb': 100, 'num_pdbs': 1, 'pdb_prefix': 'pdb', 'oracle_db_name': 'orcl', 'state': 'present', 'oracle_edition': 'EE', 'oracle_database_type': 'MULTIPURPOSE', 'oracle_version_db': '12.1.0.2'}, 'warnings': [], 'delta': '0:00:00.012415', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u'grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l'}, 'stdout_lines': ['0'], 'start': '2016-02-29 12:21:00.335741'}]) => {"changed": true, "cmd": "export PATH='$PATH:/u01/app/oracle/12.1.0.2/home1/bin'; export LD_LIBRARY_PATH='$LD_LIBRARY_PATH:/u01/app/oracle/12.1.0.2/home1/lib'; time /u01/app/oracle/12.1.0.2/home1/bin/dbca -responseFile /u01/stage/rsp/dbca_orcl.rsp -silent -redoLogFileSize 100", "delta": "0:00:04.049797", "end": "2016-02-29 12:21:05.187685", "item": [{"home": "home1", "is_container": "false", "is_racone": "false", "num_pdbs": 1, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_percent": 30, "oracle_db_name": "orcl", "oracle_db_passwd": "Oracle123", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_init_params": "open_cursors=300,processes=700", "oracle_version_db": "12.1.0.2", "pdb_prefix": "pdb", "redolog_size_in_mb": 100, "service_name": "orcl_serv", "state": "present", "storage_type": "FS"}, {"changed": true, "cmd": "grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l", "delta": "0:00:00.012415", "end": "2016-02-29 12:21:00.348156", "invocation": {"module_args": "grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l", "module_complex_args": {}, "module_name": "shell"}, "item": {"home": "home1", "is_container": "false", "is_racone": "false", "num_pdbs": 1, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_percent": 30, "oracle_db_name": "orcl", "oracle_db_passwd": "Oracle123", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_init_params": "open_cursors=300,processes=700", "oracle_version_db": "12.1.0.2", "pdb_prefix": "pdb", "redolog_size_in_mb": 100, "service_name": "orcl_serv", "state": "present", "storage_type": "FS"}, "rc": 0, "start": "2016-02-29 12:21:00.335741", "stderr": "", "stdout": "0", "stdout_lines": ["0"], "warnings": []}], "rc": 1, "start": "2016-02-29 12:21:01.137888", "warnings": []}
stderr:
real	0m4.047s
user	0m3.011s
sys	0m0.339s
stdout: Cleaning up failed steps
5% complete
Copying database files
7% complete
8% complete
9% complete
DBCA Operation failed.
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/orcl/orcl4.log" for further details.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/vagrant/my-single-instance-install.retry

localhost                  : ok=65   changed=9    unreachable=0    failed=1


real	1m47.695s
user	0m5.501s
sys	0m4.417s
```

All other useful files like:
 — /u01/app/oracle/cfgtoollogs/dbca/orcl/orcl4.log;
 — /u01/app/oracle/cfgtoollogs/dbca/orcl/trace.log;
 — my-single-instance-install.yml
are in attachment.

[orcl4.txt](https://github.com/oravirt/ansible-oracle/files/150850/orcl4.txt)
[trace.txt](https://github.com/oravirt/ansible-oracle/files/150851/trace.txt)
[my-single-instance-install.txt](https://github.com/oravirt/ansible-oracle/files/150852/my-single-instance-install.txt)

**Comment by oravirt** [comment]
Hi,
I cant remember I've seen that error before. I just did a clean install on a Centos 6.7 box (box-cutter/centos67) as well and that worked.
Do you have a Vagrantfile I can test with? Have you done any changes to the defaults, like setup group_vars/mygroup or something like that?

**Comment by tischenko** [comment]
I tried to use _box-cutter/centos67_ today and got the same error. Below I'll try to explain all my steps sequentially. I also need to mention here, that I run ansible from inside my vagrant box (manually, without provisioners), so basically ansible just has to ssh to localhost under user _vagrant_.
— Start new VM from _box-cutter/centos67_ with default settings, changed just amount of RAM for VM (increased to 2048 mb). _Vagrantfile_ is in attachment.
— Enable EPEL repo installing _epel-release-latest-6.noarch.rpm_.
— Install _vim_, _git_, _ansible (1.9.4)_.
— Clone git repo.
— Generate ssh-key for user _vagrant_ and add pub-key into _authorized_hosts_ for user _vagrant_ to allow ssh to localhost with a key under user _vagrant_.
— _echo "127.0.0.1 oradb03" > /etc/hosts_
— Create _inventory/hosts_ and _my-single-instance-install.yml_ in compliance with [https://oravirt.wordpress.com/2014/10/01/getting-started-with-ansible-oracle/](https://oravirt.wordpress.com/2014/10/01/getting-started-with-ansible-oracle/)
```
[mygroup]
oradb03
```
```
---
 - name: Host configuration
   hosts: mygroup
   user: vagrant
   sudo: yes
   roles:
    - common
    - orahost
 - name: Oracle Database server installation & Database Creation
   hosts: mygroup
   user: vagrant
   sudo: yes
   sudo_user: oracle
   roles:
    - oraswdb-install
    - oradb-create
```
— Create _group_vars/mygroup_.
```
---
  is_sw_source_local: true
  install_from_nfs: false
```
— Put _linuxamd64_12102_database_1of2.zip_ and _linuxamd64_12102_database_2of2.zip_ into _/tmp/_.
— Run ansible under user _vagrant_ like _time ansible-playbook my-single-instance-install.yml -i inventory/hosts_.

First after this run I get such error:
_GPG key retrieval failed: [Errno 14] Could not open/read file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle_
Don't have full trace here, but pretty sure this raises in _common_ role.

Have to fix it manually:
_rpm --import http://oss.oracle.com/ol6/RPM-GPG-KEY-oracle_
_rpm -q gpg-pubkey-ec551f03-4c2d256_

After next run I get another error:
_msg: Destination /etc not writable._
This also raises in _common_ role. Seems like issues in _template_ module with _sudo_.

So to fix this issue, I have to switch to _root_ user, and modify my _my-single-instance-install.yml_ this way (also add _-k_ to ansible run):
```
---
 - name: Host configuration
   hosts: mygroup
   user: root
   sudo: no
   roles:
    - common
    - orahost
 - name: Oracle Database server installation & Database Creation
   hosts: mygroup
   user: root
   sudo: no
   sudo_user: oracle
   roles:
    - oraswdb-install
    - oradb-create
```

After this it works fine till _oradb-create | Create database(s)_ step. There I get this:
```
failed: [oradb03] => (item=[{'oracle_init_params': 'open_cursors=300,processes=700', 'is_racone': 'false', 'oracle_db_type': 'SI', 'service_name': 'orcl_serv', 'storage_type': 'FS', 'oracle_db_passwd': 'Oracle123', 'home': 'home1', 'oracle_db_mem_percent': 30, 'is_container': 'false', 'redolog_size_in_mb': 100, 'num_pdbs': 1, 'pdb_prefix': 'pdb', 'oracle_db_name': 'orcl', 'state': 'present', 'oracle_edition': 'EE', 'oracle_database_type': 'MULTIPURPOSE', 'oracle_version_db': '12.1.0.2'}, {'cmd': 'grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l', 'end': '2016-03-01 13:12:36.783826', 'stderr': '', 'stdout': '0', 'changed': True, 'rc': 0, 'item': {'oracle_init_params': 'open_cursors=300,processes=700', 'is_racone': 'false', 'oracle_db_type': 'SI', 'service_name': 'orcl_serv', 'storage_type': 'FS', 'oracle_db_passwd': 'Oracle123', 'home': 'home1', 'oracle_db_mem_percent': 30, 'is_container': 'false', 'redolog_size_in_mb': 100, 'num_pdbs': 1, 'pdb_prefix': 'pdb', 'oracle_db_name': 'orcl', 'state': 'present', 'oracle_edition': 'EE', 'oracle_database_type': 'MULTIPURPOSE', 'oracle_version_db': '12.1.0.2'}, 'warnings': [], 'delta': '0:00:00.003707', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u'grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l'}, 'stdout_lines': ['0'], 'start': '2016-03-01 13:12:36.780119'}]) => {"changed": true, "cmd": "time /u01/app/oracle/12.1.0.2/home1/bin/dbca -responseFile /u01/stage/rsp/dbca_orcl.rsp -silent -redoLogFileSize 100", "delta": "0:00:05.086495", "end": "2016-03-01 13:12:42.809992", "item": [{"home": "home1", "is_container": "false", "is_racone": "false", "num_pdbs": 1, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_percent": 30, "oracle_db_name": "orcl", "oracle_db_passwd": "Oracle123", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_init_params": "open_cursors=300,processes=700", "oracle_version_db": "12.1.0.2", "pdb_prefix": "pdb", "redolog_size_in_mb": 100, "service_name": "orcl_serv", "state": "present", "storage_type": "FS"}, {"changed": true, "cmd": "grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l", "delta": "0:00:00.003707", "end": "2016-03-01 13:12:36.783826", "invocation": {"module_args": "grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l", "module_complex_args": {}, "module_name": "shell"}, "item": {"home": "home1", "is_container": "false", "is_racone": "false", "num_pdbs": 1, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_percent": 30, "oracle_db_name": "orcl", "oracle_db_passwd": "Oracle123", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_init_params": "open_cursors=300,processes=700", "oracle_version_db": "12.1.0.2", "pdb_prefix": "pdb", "redolog_size_in_mb": 100, "service_name": "orcl_serv", "state": "present", "storage_type": "FS"}, "rc": 0, "start": "2016-03-01 13:12:36.780119", "stderr": "", "stdout": "0", "stdout_lines": ["0"], "warnings": []}], "rc": 1, "start": "2016-03-01 13:12:37.723497", "warnings": []}
stderr:
real	0m5.084s
user	0m3.313s
sys	0m0.300s
stdout: Copying database files
1% complete
2% complete
4% complete
DBCA Operation failed.
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/orcl/orcl.log" for further details.

FATAL: all hosts have already failed -- aborting
```
_orcl.log_ you can find in my previous comment.

I'm a very beginner with ansible, so probably I just do something wrong. All what I want here is to install Oracle DB, running ansible from inside my vagrant box. 

[Vagrantfile.txt](https://github.com/oravirt/ansible-oracle/files/152870/Vagrantfile.txt)

**Comment by oravirt** [comment]
Hi,

Ok, I've changed a few things in the way the roles work so there are few things that I need to change in the blogpost as well. I'll fix that as soon as possible.

There are also a few things that I haven't pushed to the repo yet (like only adding the Oracle Linux 
public yum repo if you're actually running on Oracle Linux), so that should solve the key issue.

In the meantime, you can try this and hopefully that'll work
In your group_vars/mygroup add the following line:
```
configure_public_yum_repo: false 
```
That will just skip the step of adding the repo to the host and then you don't have to add the keys manually

You should also change your playbook to remove the sudo_user directive, so it should look like this.
```
---
 - name: Host configuration
   hosts: mygroup
   user: root
   sudo: yes
   roles:
    - common
    - orahost
 - name: Oracle Database server installation & Database Creation
   hosts: mygroup
   user: root
   sudo: yes
   roles:
    - oraswdb-install
    - oradb-create
```

Try that and see if it works. I haven't had time to test this again but that should hopefully do the trick.
Let me know how it goes!

**Comment by tischenko** [comment]
Hi,

Thank you for your help.
I've tried this way today (added _configure_public_yum_repo_ option and updated _my-single-instance-install.yml_). 
This fixed problems with repo and "/etc not writable", but main problem is still here:
```
TASK: [oradb-create | Create database(s)] *************************************
failed: [oradb03] => (item=[{'oracle_init_params': 'open_cursors=300,processes=700', 'is_racone': 'false', 'oracle_db_type': 'SI', 'service_name': 'orcl_serv', 'storage_type': 'FS', 'oracle_db_passwd': 'Oracle123', 'home': 'home1', 'oracle_db_mem_percent': 30, 'is_container': 'false', 'redolog_size_in_mb': 100, 'num_pdbs': 1, 'pdb_prefix': 'pdb', 'oracle_db_name': 'orcl', 'state': 'present', 'oracle_edition': 'EE', 'oracle_database_type': 'MULTIPURPOSE', 'oracle_version_db': '12.1.0.2'}, {'cmd': 'grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l', 'end': '2016-03-03 09:05:46.141635', 'stderr': '', 'stdout': '0', 'changed': True, 'rc': 0, 'item': {'oracle_init_params': 'open_cursors=300,processes=700', 'is_racone': 'false', 'oracle_db_type': 'SI', 'service_name': 'orcl_serv', 'storage_type': 'FS', 'oracle_db_passwd': 'Oracle123', 'home': 'home1', 'oracle_db_mem_percent': 30, 'is_container': 'false', 'redolog_size_in_mb': 100, 'num_pdbs': 1, 'pdb_prefix': 'pdb', 'oracle_db_name': 'orcl', 'state': 'present', 'oracle_edition': 'EE', 'oracle_database_type': 'MULTIPURPOSE', 'oracle_version_db': '12.1.0.2'}, 'warnings': [], 'delta': '0:00:00.003762', 'invocation': {'module_name': u'shell', 'module_complex_args': {}, 'module_args': u'grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l'}, 'stdout_lines': ['0'], 'start': '2016-03-03 09:05:46.137873'}]) => {"changed": true, "cmd": "time /u01/app/oracle/12.1.0.2/home1/bin/dbca -responseFile /u01/stage/rsp/dbca_orcl.rsp -silent -redoLogFileSize 100", "delta": "0:00:04.943096", "end": "2016-03-03 09:05:52.008775", "item": [{"home": "home1", "is_container": "false", "is_racone": "false", "num_pdbs": 1, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_percent": 30, "oracle_db_name": "orcl", "oracle_db_passwd": "Oracle123", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_init_params": "open_cursors=300,processes=700", "oracle_version_db": "12.1.0.2", "pdb_prefix": "pdb", "redolog_size_in_mb": 100, "service_name": "orcl_serv", "state": "present", "storage_type": "FS"}, {"changed": true, "cmd": "grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l", "delta": "0:00:00.003762", "end": "2016-03-03 09:05:46.141635", "invocation": {"module_args": "grep orcl:/u01/app/oracle/12.1.0.2/home1 /etc/oratab |wc -l", "module_complex_args": {}, "module_name": "shell"}, "item": {"home": "home1", "is_container": "false", "is_racone": "false", "num_pdbs": 1, "oracle_database_type": "MULTIPURPOSE", "oracle_db_mem_percent": 30, "oracle_db_name": "orcl", "oracle_db_passwd": "Oracle123", "oracle_db_type": "SI", "oracle_edition": "EE", "oracle_init_params": "open_cursors=300,processes=700", "oracle_version_db": "12.1.0.2", "pdb_prefix": "pdb", "redolog_size_in_mb": 100, "service_name": "orcl_serv", "state": "present", "storage_type": "FS"}, "rc": 0, "start": "2016-03-03 09:05:46.137873", "stderr": "", "stdout": "0", "stdout_lines": ["0"], "warnings": []}], "rc": 1, "start": "2016-03-03 09:05:47.065679", "warnings": []}
stderr:
real	0m4.940s
user	0m3.096s
sys	0m0.318s
stdout: Copying database files
1% complete
2% complete
4% complete
DBCA Operation failed.
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/orcl/orcl.log" for further details.

FATAL: all hosts have already failed -- aborting
```

**Comment by oravirt** [comment]
Hi,

Ok, great.
I think the dbca issue maybe is a resource issue. 
I dont have anywhere to test this at the moment, but try to raise the amount of RAM on the VM to say 3GB and run the playbook again. I'll see if I can test this tonight.

**Comment by tischenko** [comment]
Hi,
I've tried to increase RAM to 6GB and this didn't work.

**Comment by oravirt** [comment]
Did you re-run the entire playbook (orahost etc)? Not only try to create the database. I base some kernel-parameters on the amount of RAM etc so it might be a good idea to run that as well

**Comment by tischenko** [comment]
Yep, I tried to start with new VM and 6GB of RAM, but this didn't work.

**Comment by oravirt** [comment]
I'm sorry, but I can't reproduce this. I get the error when I set the RAM to 2G, but if I set it to 3GB it works. Did you also try to recreate the VM with 3G (as in vagrant destroy, vagrant up)
Other than that, I'm not sure what else I can do.

**Comment by tischenko** [comment]
Sorry, for late reply. Still can't get over this error. So decided to start my own playbook from scratch.
Anyway thank you for your support and time.

**Comment by oravirt** [comment]
Ok, sorry to hear it didn't work out
